using System.Globalization;
using Marketplace.Shared.Results;
using MediatR;

namespace Marketplace.Application.Localization.Queries.GetLocalizationStrings;

public sealed record GetLocalizationStringsQuery(string? LanguageCode = null) : IRequest<Result<Dictionary<string, string>>>;

public sealed class GetLocalizationStringsQueryHandler : IRequestHandler<GetLocalizationStringsQuery, Result<Dictionary<string, string>>>
{
    public Task<Result<Dictionary<string, string>>> Handle(GetLocalizationStringsQuery request, CancellationToken cancellationToken)
    {
        var rawLang = request.LanguageCode ?? CultureInfo.CurrentUICulture.Name;
        var culture = rawLang.ToLowerInvariant();
        var isPashto = culture.Contains("ps");
        var isDari = culture.Contains("prs") || culture.Contains("fa") || culture.Contains("dr");

        var strings = new Dictionary<string, string>
        {
            // Core & Navigation
            ["AppName"] = isPashto ? "د نورزي بازار" : (isDari ? "بازار نورزی" : "BuyMore"),
            ["PopularProducts"] = isPashto ? "مشهور توکي" : (isDari ? "محصولات محبوب" : "Popular Products"),
            ["ExploreNew"] = isPashto ? "نوې موندنې" : (isDari ? "کشف جدید" : "Explore New"),
            ["ClothingAndShoes"] = isPashto ? "جامې او بوټان" : (isDari ? "پوشاک و کفش" : "Clothing and Shoes"),
            ["GiftsAndLiving"] = isPashto ? "ډالۍ او د کور سامان" : (isDari ? "هدایا و لوازم منزل" : "Gifts and Living"),
            ["Inspiration"] = isPashto ? "الهام" : (isDari ? "الهام‌بخش" : "Inspiration"),
            ["QuickActions"] = isPashto ? "چټک اقدامات" : (isDari ? "اقدامات سریع" : "Quick actions"),
            ["LogIn"] = isPashto ? "حساب ته ننوتل" : (isDari ? "ورود به حساب" : "Log in"),
            ["SignUp"] = isPashto ? "نوم لیکنه" : (isDari ? "ثبت‌نام" : "Sign up"),
            ["LogOut"] = isPashto ? "وتل" : (isDari ? "خروج" : "Log out"),
            ["MyOrders"] = isPashto ? "زما فرمایشونه" : (isDari ? "سفارشات من" : "My Orders"),
            ["Profile"] = isPashto ? "پروفایل" : (isDari ? "پروفایل کاربری" : "Profile"),
            ["AdminPanel"] = isPashto ? "د ادارې پنل" : (isDari ? "پنل مدیریت" : "Admin Panel"),
            ["Cart"] = isPashto ? "ټوکرۍ" : (isDari ? "سبد خرید" : "Cart"),
            ["Explore"] = isPashto ? "کاوش" : (isDari ? "کاوش" : "Explore"),
            ["All"] = isPashto ? "ټول" : (isDari ? "همه" : "All"),
            ["Men"] = isPashto ? "سړي" : (isDari ? "مردانه" : "Men"),
            ["Women"] = isPashto ? "ښځې" : (isDari ? "زنانه" : "Women"),
            ["Filters"] = isPashto ? "فیلټرونه" : (isDari ? "فیلترها" : "Filters"),
            ["Search"] = isPashto ? "لټون" : (isDari ? "جستجو" : "Search"),
            ["SeeAll"] = isPashto ? "ټول لیدل" : (isDari ? "مشاهده همه" : "See All"),
            ["Dashboard"] = isPashto ? "ډشبورډ" : (isDari ? "داشبورد" : "Dashboard"),
            ["Website"] = isPashto ? "ویب پاڼه" : (isDari ? "وب‌سایت" : "Website"),
            ["BackToStore"] = isPashto ? "← زېرمې ته ستنېدل" : (isDari ? "← بازگشت به فروشگاه" : "← Back to Store"),

            // Banners & Discounts
            ["GetUpTo50Off"] = isPashto ? "تر ۵۰٪ پورې تخفیف ترلاسه کړئ" : (isDari ? "تا ۵۰٪ تخفیف طلایی دریافت کنید" : "GET UP TO 50% OFF"),
            ["GetDiscount"] = isPashto ? "تخفیف ترلاسه کول" : (isDari ? "دریافت تخفیف" : "Get Discount"),
            ["WinterWeekend"] = isPashto ? "د ژمي رخصتۍ" : (isDari ? "تعطیلات زمستانی" : "Winter's weekend"),
            ["KeepItCasual"] = isPashto ? "کژوال او هوسا سټایل" : (isDari ? "استایل راحت و خاص" : "keep it casual"),
            ["OurPicks"] = isPashto ? "زموږ انتخاب" : (isDari ? "انتخاب ما" : "Our Picks"),
            ["YourChoice"] = isPashto ? "ستاسو انتخاب" : (isDari ? "انتخاب شما" : "Your Choice"),
            ["AvailOffers"] = isPashto ? "وړاندیزونه وګورئ" : (isDari ? "مشاهده پیشنهادات" : "Avail Offers"),
            ["Favourites"] = isPashto ? "غوره شوي" : (isDari ? "محبوب‌ترین‌ها" : "Favourites"),
            ["BringBoldFashion"] = isPashto ? "په زړه پورې فیشن" : (isDari ? "مد و فیشن جسورانه" : "Bring Bold Fashion"),
            ["LayersOnLayers"] = isPashto ? "لایه په لایه سټایلونه" : (isDari ? "لایه در لایه و خاص" : "Layers on Layers"),

            // Admin & Inventory Management
            ["ProductsInventory"] = isPashto ? "د توکو فهرست" : (isDari ? "فهرست محصولات" : "Products Inventory"),
            ["ManageCatalogItems"] = isPashto ? "د کتلاګ توکي، نرخونه او موجودي اداره کړئ" : (isDari ? "مدیریت اقلام کاتالوگ، قیمت‌ها و موجودی" : "Manage active catalog items, prices, and stock"),
            ["AddNewProduct"] = isPashto ? "+ نوی توکی زیاتول" : (isDari ? "+ افزودن محصول جدید" : "+ Add New Product"),
            ["SuperAdminView"] = isPashto ? "👑 سوپر اډمین (د ټول پلورونکو توکي)" : (isDari ? "👑 سوپر ادمین (تمامی محصولات فروشندگان)" : "👑 SuperAdmin (All Vendor Products)"),
            ["VendorScopedView"] = isPashto ? "🏪 د پلورونکي لید (یوازې زما توکي)" : (isDari ? "🏪 لید اختصاصی فروشنده (محصولات من)" : "🏪 Vendor Scoped (My Products Only)"),
            ["MultilingualProductTitles"] = isPashto ? "په بېلابېلو ژبو کې د توکي نومونه" : (isDari ? "عناوین چندزبانه محصول" : "Multilingual Product Titles"),
            ["ProductImageGallery"] = isPashto ? "د توکي انځورونو ګالري" : (isDari ? "گالری تصاویر محصول" : "Product Image Gallery"),
            ["UploadImageFile"] = isPashto ? "د انځور فایل اپلوډ کول" : (isDari ? "آپلود فایل تصویر" : "Upload Image File"),
            ["OrDirectImageUrl"] = isPashto ? "یا د انځور مستقيمه لینک" : (isDari ? "یا لینک مستقیم تصویر" : "Or Direct Image URL"),
            ["PriceUSD"] = isPashto ? "قیمت (ډالر USD)" : (isDari ? "قیمت (دلار USD)" : "Price ($ USD)"),
            ["StockQuantity"] = isPashto ? "موجودي شمیره" : (isDari ? "تعداد موجودی" : "Stock Quantity"),
            ["Category"] = isPashto ? "کتګوري" : (isDari ? "دسته‌بندی" : "Category"),
            ["VendorStoreOwner"] = isPashto ? "پلورونکی / د دوکان مالک" : (isDari ? "فروشنده / مالک فروشگاه" : "Vendor / Store Owner"),
            ["CustomSpecifications"] = isPashto ? "د توکي ځانګړي مشخصات او ځانګړتیاوې" : (isDari ? "مشخصات و ویژگی‌های سفارشی محصول" : "Custom Product Specifications & Attributes"),
            ["AddAttribute"] = isPashto ? "+ ځانګړتیا زیاتول" : (isDari ? "+ افزودن ویژگی" : "+ Add Attribute"),
            ["SaveNewProduct"] = isPashto ? "نوی توکی خوندي کول" : (isDari ? "ذخیره محصول جدید" : "Save New Product"),
            ["UpdateProduct"] = isPashto ? "توکی تازه کول" : (isDari ? "به‌روزرسانی محصول" : "Update Product"),
            ["DeleteProductConfirm"] = isPashto ? "ایا تاسو ډاډه یاست چې غواړئ دا توکی حذف کړئ؟" : (isDari ? "آیا از حذف این محصول اطمینان دارید؟" : "Are you sure you want to delete this product?"),
            ["Cancel"] = isPashto ? "لغوه کول" : (isDari ? "انصراف" : "Cancel"),
            ["Delete"] = isPashto ? "حذف کول" : (isDari ? "حذف" : "Delete"),
            ["Processing"] = isPashto ? "د پروسس په حال کې..." : (isDari ? "در حال پردازش..." : "Processing..."),
            ["Saving"] = isPashto ? "د خوندي کولو په حال کې..." : (isDari ? "در حال ذخیره..." : "Saving..."),

            // Vendor & Agency Approvals
            ["VendorAgencyApprovals"] = isPashto ? "د پلورونکو او نمایندګیو تایید" : (isDari ? "تایید فروشندگان و نمایندگی‌ها" : "Vendor & Agency Approvals"),
            ["ReviewApplicantDetails"] = isPashto ? "د غوښتونکي توضیحات، بانکي معلومات بررسی کړئ او پرېکړه وکړئ" : (isDari ? "بررسی مشخصات متقاضیان، اطلاعات بانکی و اتخاذ تصمیم" : "Review applicant details, bank account verification, and make decisions"),
            ["ShopAgencyName"] = isPashto ? "د پلورنځي / نمایندګۍ نوم" : (isDari ? "نام فروشگاه / نمایندگی" : "Shop / Agency Name"),
            ["DescriptionDetails"] = isPashto ? "توضیحات او اسناد" : (isDari ? "توضیحات و مدارک" : "Description & Details"),
            ["BankAccountInfo"] = isPashto ? "د بانکي حساب معلومات" : (isDari ? "اطلاعات حساب بانکی" : "Bank Account Info"),
            ["VerificationStatus"] = isPashto ? "د تایید حالت" : (isDari ? "وضعیت تایید" : "Verification Status"),
            ["DecisionActions"] = isPashto ? "پرېکړه / اقدامات" : (isDari ? "تصمیم‌گیری / اقدامات" : "Decision / Actions"),
            ["Approve"] = isPashto ? "✓ تایید کول" : (isDari ? "✓ تایید" : "✓ Approve"),
            ["Reject"] = isPashto ? "✕ رد کول" : (isDari ? "✕ رد" : "✕ Reject"),
            ["VerifiedMerchant"] = isPashto ? "✓ تایید شوی پلورونکی" : (isDari ? "✓ فروشنده تاییدشده" : "✓ Verified Merchant"),
            ["PendingApproval"] = isPashto ? "⏳ د تایید په تمه" : (isDari ? "⏳ در انتظار تایید" : "⏳ Pending Approval"),
            ["NoPendingApplications"] = isPashto ? "هیڅ پاتې غوښتنه ونه موندل شوه." : (isDari ? "هیچ درخواستی یافت نشد." : "No pending applications found."),
            ["RegisterAsVendor"] = isPashto ? "د پلورونکي په توګه نوم لیکنه" : (isDari ? "ثبت‌نام به عنوان فروشنده" : "Register as Vendor"),
            ["CreateYourOnlineShop"] = isPashto ? "خپل آنلاین پلورنځی جوړ کړئ" : (isDari ? "فروشگاه آنلاین خود را بسازید" : "Create Your Online Shop"),
            ["ShopNameEnglish"] = isPashto ? "د پلورنځي نوم (انګلیسي)" : (isDari ? "نام فروشگاه (انگلیسی)" : "Shop Name (English)"),
            ["ShopNameDari"] = isPashto ? "د پلورنځي نوم (دري)" : (isDari ? "نام فروشگاه (دری)" : "Shop Name (Dari)"),
            ["ShopNamePashto"] = isPashto ? "د پلورنځي نوم (پښتو)" : (isDari ? "نام فروشگاه (پښتو)" : "Shop Name (Pashto)"),
            ["SubmitVendorRegistration"] = isPashto ? "د پلورونکي ثبت ثبت کول" : (isDari ? "ثبت درخواست فروشندگی" : "Submit Vendor Registration"),

            // Agency Application Page
            ["AgencyApplication"] = isPashto ? "د رسمي نمایندګۍ غوښتنه" : (isDari ? "فرم درخواست اخذ نمایندگی رسمی" : "Agency Application"),
            ["ApplicantDetails"] = isPashto ? "د غوښتونکي او سوداګرۍ معلومات" : (isDari ? "مشخصات متقاضی و کسب‌وکار" : "Applicant & Business Details"),
            ["ApplicantNameCompany"] = isPashto ? "د غوښتونکي / شرکت نوم" : (isDari ? "نام متقاضی / شرکت" : "Applicant Name / Company"),
            ["ProvinceCity"] = isPashto ? "ولایت او ښار" : (isDari ? "استان و شهر" : "Province & City"),
            ["DirectPhone"] = isPashto ? "مستقیم تلیفون شمیره" : (isDari ? "شماره تلفن مستقیم" : "Direct Phone Number"),
            ["BusinessLicense"] = isPashto ? "د سوداګرۍ جواز شمیره (اختیاري)" : (isDari ? "شماره جواز کسب (اختیاری)" : "Business License Number (Optional)"),
            ["BusinessCategorySector"] = isPashto ? "د سوداګرۍ برخه / سکتور" : (isDari ? "رسته شغلی / حوزه فعالیت" : "Business Category / Sector"),
            ["AdditionalDetailsFacilities"] = isPashto ? "اضافي توضیحات او امکانات" : (isDari ? "توضیحات و امکانات جانبی" : "Additional Details & Facilities"),
            ["SubmitAgencyApplication"] = isPashto ? "د نمایندګۍ غوښتنه لیږل" : (isDari ? "ثبت نهایی درخواست نمایندگی" : "Submit Agency Application"),

            // Orders Management
            ["OrderManagement"] = isPashto ? "د فرمایشونو مدیریت" : (isDari ? "مدیریت سفارشات" : "Order Management"),
            ["ReviewOrders"] = isPashto ? "د پیرودونکو فرمایشونه او تعقیب حالت وګورئ" : (isDari ? "بررسی سفارشات مشتریان و وضعیت پیگیری" : "Review customer orders, update tracking status"),
            ["OrderID"] = isPashto ? "د فرمایش آی ډي" : (isDari ? "شناسه سفارش" : "Order ID"),
            ["Customer"] = isPashto ? "پیرودونکی" : (isDari ? "مشتری" : "Customer"),
            ["Amount"] = isPashto ? "مبلغ" : (isDari ? "مبلغ" : "Amount"),
            ["Date"] = isPashto ? "نیټه" : (isDari ? "تاریخ" : "Date"),
            ["Status"] = isPashto ? "حالت" : (isDari ? "وضعیت" : "Status"),
            ["ChangeStatus"] = isPashto ? "حالت بدلول" : (isDari ? "تغییر وضعیت" : "Change Status"),
            ["Pending"] = isPashto ? "در انتظار" : (isDari ? "در انتظار" : "Pending"),
            ["Paid"] = isPashto ? "پرداخت شده" : (isDari ? "پرداخت شده" : "Paid"),
            ["Shipped"] = isPashto ? "ارسال شده" : (isDari ? "ارسال شده" : "Shipped"),
            ["Completed"] = isPashto ? "تکمیل شده" : (isDari ? "تکمیل شده" : "Completed"),
            ["Cancelled"] = isPashto ? "لغوه شده" : (isDari ? "لغوه شده" : "Cancelled"),

            // Product Details Page
            ["LoadingProductDetails"] = isPashto ? "د محصول د بشپړ معلوماتو بارول..." : (isDari ? "در حال بارگذاری اطلاعات کامل محصول..." : "Loading complete product details..."),
            ["Home"] = isPashto ? "کور" : (isDari ? "خانه" : "Home"),
            ["GeneralProduct"] = isPashto ? "عمومي توکي" : (isDari ? "کالای عمومی" : "General Product"),
            ["ProductCode"] = isPashto ? "د توکو کوډ:" : (isDari ? "کد کالا:" : "SKU / Code:"),
            ["Vendor"] = isPashto ? "پلورونکی:" : (isDari ? "فروشنده:" : "Vendor:"),
            ["Share"] = isPashto ? "شریکول" : (isDari ? "اشتراک‌گذاری" : "Share"),
            ["LinkCopied"] = isPashto ? "د محصول د پاڼې لینک په کلیپ بورډ کې کاپي شو." : (isDari ? "لینک صفحه محصول در کلیپ‌بورد کپی شد." : "Product link copied to clipboard."),
            ["AddToWishlist"] = isPashto ? "خوښول" : (isDari ? "نشان کردن" : "Bookmark"),
            ["Favorited"] = isPashto ? "خوښ شوی" : (isDari ? "علاقه‌مندی" : "Favorited"),
            ["AddedToWishlist"] = isPashto ? "د خوښې وړ لیست کې اضافه شو!" : (isDari ? "به لیست علاقه‌مندی‌ها افزوده شد!" : "Added to your wishlist!"),
            ["RemovedFromWishlist"] = isPashto ? "د خوښې وړ لیست څخه لرې شو." : (isDari ? "از لیست علاقه‌مندی‌ها حذف شد." : "Removed from your wishlist."),
            ["InStock"] = isPashto ? "په ګودام کې شتون لري" : (isDari ? "موجود در انبار" : "In Stock"),
            ["OutOfStock"] = isPashto ? "شتون نلري" : (isDari ? "ناموجود" : "Out of Stock"),
            ["TopRated"] = isPashto ? "غوره توکي" : (isDari ? "کالای برگزیده" : "Top Rated"),
            ["ClickToExpand"] = isPashto ? "د انځور د لویولو لپاره کلیک وکړئ" : (isDari ? "کلیک برای بزرگنمایی تصویر" : "Click to expand image"),
            ["CustomerReviewsCount"] = isPashto ? "(د ۱۲۸ پیرودونکو نظرونه)" : (isDari ? "(۱۲۸ امتیاز خریداران)" : "(128 customer reviews)"),
            ["BuyerSatisfactionRate"] = isPashto ? "۹۶٪ پیرودونکي د دې توکو کیفیت وړاندیز کوي" : (isDari ? "۹۶٪ رضایت خریداران از کیفیت کالا" : "96% of buyers recommended this item"),
            ["FinalPriceWithDiscount"] = isPashto ? "وروستۍ بیه له تخفیف سره:" : (isDari ? "قیمت نهایی با احتساب تخفیف:" : "Final price including discounts:"),
            ["BestPriceGuarantee"] = isPashto ? "د غوره بیې تضمین" : (isDari ? "تضمین بهترین قیمت" : "Best Price Guarantee"),
            ["WarehouseStock"] = isPashto ? "د ګودام شتون:" : (isDari ? "موجودی انبار:" : "Warehouse Stock:"),
            ["UnitsReadyToShip"] = isPashto ? "عدده د لیږلو لپاره چمتو دي" : (isDari ? "عدد آماده ارسال" : "units ready to ship"),
            ["SelectSize"] = isPashto ? "اندازه وټاکئ:" : (isDari ? "انتخاب سایز:" : "Select Size:"),
            ["SelectColor"] = isPashto ? "رنګ وټاکئ:" : (isDari ? "انتخاب رنگ:" : "Select Color:"),
            ["AddToCart"] = isPashto ? "ټوکرۍ ته زیاتول" : (isDari ? "افزودن به سبد خرید" : "Add to Cart"),
            ["AddedToCart"] = isPashto ? "✓ ټوکرۍ ته زیات شو!" : (isDari ? "✓ به سبد خرید اضافه شد!" : "✓ Added to cart!"),
            ["BuyNow"] = isPashto ? "فوري پیرود" : (isDari ? "خرید آنی" : "Buy Now"),
            ["ShoppingCart"] = isPashto ? "د پیرودلو ټوکرۍ" : (isDari ? "سبد خرید" : "Shopping Cart"),
            ["AuthenticGuarantee"] = isPashto ? "د ۱۰۰٪ اصالت تضمین" : (isDari ? "ضمانت اصالت ۱۰۰٪" : "100% Authentic"),
            ["AuthenticDesc"] = isPashto ? "اصلي او اوریجنل توکي" : (isDari ? "کالای اصل و اورجینال" : "Original & genuine product"),
            ["FastDelivery"] = isPashto ? "ګړندی او بیمه شوی لیږد" : (isDari ? "ارسال سریع و بیمه" : "Fast & Insured Delivery"),
            ["FastDeliveryDesc"] = isPashto ? "د کور مخې ته تحویل" : (isDari ? "تحویل درب منزل" : "Direct home delivery"),
            ["ReturnGuarantee"] = isPashto ? "۷ ورځې د بیرته ستنیدو تضمین" : (isDari ? "۷ روز ضمانت بازگشت" : "7-Day Return Guarantee"),
            ["ReturnGuaranteeDesc"] = isPashto ? "د نه رضایت په صورت کې" : (isDari ? "در صورت عدم رضایت" : "If not fully satisfied"),
            ["Support247"] = isPashto ? "۲۴/۷ ملاتړ" : (isDari ? "پشتیبانی ۲۴/۷" : "24/7 Support"),
            ["Support247Desc"] = isPashto ? "آنلاین ځواب ویل" : (isDari ? "پاسخگویی آنلاین" : "Online customer care"),
            ["TabOverview"] = isPashto ? "د محصول توضیحات او بیاکتنه" : (isDari ? "توضیحات و نقد محصول" : "Overview & Review"),
            ["TabSpecs"] = isPashto ? "تخنیکي مشخصات او ځانګړتیاوې" : (isDari ? "مشخصات فنی و ویژگی‌ها" : "Specifications"),
            ["TabVendor"] = isPashto ? "د پلورونکي او استازیتوب مشخصات" : (isDari ? "مشخصات فروشنده و نمایندگی" : "Vendor & Store Info"),
            ["TabReviews"] = isPashto ? "د پیرودونکو نظرونه او بیاکتنې" : (isDari ? "دیدگاه و نظرات خریداران" : "Customer Reviews"),
            ["OverviewHeading"] = isPashto ? "د محصول پیژندنه او تخصصي بیاکتنه" : (isDari ? "معرفی و بررسی تخصصی محصول" : "Product Overview & Expert Review"),
            ["NoOverviewText"] = isPashto ? "د دې محصول لپاره اضافي توضیحات نشته." : (isDari ? "توضیحات تکمیلی برای این محصول درج نشده است." : "No additional description available for this product."),
            ["Feature1Title"] = isPashto ? "معیاري او ارګونومیک ډیزاین" : (isDari ? "طراحی استاندارد و ارگونومیک" : "Standard & Ergonomic Design"),
            ["Feature1Desc"] = isPashto ? "د لوړو نړیوالو کیفي معیارونو پراساس تولید شوی" : (isDari ? "تولید شده بر اساس بالاترین استانداردهای کیفی بین‌المللی" : "Manufactured to the highest international quality standards"),
            ["Feature2Title"] = isPashto ? "لوړ کیفیته او دوامدار خام مواد" : (isDari ? "مواد اولیه مرغوب و بادوام" : "Premium Grade Materials"),
            ["Feature2Desc"] = isPashto ? "اوږدمهاله پایښت او چاپیریال سره بشپړ مطابقت" : (isDari ? "ماندگاری طولانی و سازگار با پوست و محیط زیست" : "Long-lasting durability and skin/environment friendly"),
            ["Feature3Title"] = isPashto ? "خوندي او پلمپ شوې بسته بندي" : (isDari ? "بسته‌بندی ایمن و پلمپ" : "Secure & Sealed Packaging"),
            ["Feature3Desc"] = isPashto ? "ځانګړې بسته بندي د اصالت لیبل سره" : (isDari ? "بسته‌بندی اختصاصی کارخانه با برچسب اصالت کالا" : "Factory sealed box with authenticity guarantee seal"),
            ["SpecsHeading"] = isPashto ? "د تخنیکي مشخصاتو او ځانګړتیاوو جدول" : (isDari ? "جدول مشخصات و ویژگی‌های فنی" : "Technical Specifications Table"),
            ["NoSpecsText"] = isPashto ? "د دې محصول لپاره کوم ځانګړي تخنیکي مشخصات ندي ثبت شوي." : (isDari ? "مشخصات فنی خاصی برای این محصول ثبت نشده است." : "No specific technical attributes registered for this product."),
            ["VerifiedVendor"] = isPashto ? "رسمي او تایید شوی پلورونکی" : (isDari ? "فروشنده رسمی و تاییدشده" : "Verified Official Vendor"),
            ["VerifiedVendorDesc"] = isPashto ? "د نورزي مارکیټ د معتبرو استازو شبکې رسمي غړی" : (isDari ? "عضو رسمی شبکه نمایندگان معتبر بازار نورزی" : "Official member of Noorzai Marketplace verified partners"),
            ["ViewAllVendorProducts"] = isPashto ? "د پلورونکي ټول محصولات لیدل ←" : (isDari ? "مشاهده همه محصولات فروشنده ←" : "View All Vendor Products ←"),
            ["VendorScore"] = isPashto ? "د پلورونکي د فعالیت نمره" : (isDari ? "امتیاز عملکرد فروشنده" : "Vendor Performance Score"),
            ["OnTimeShipping"] = isPashto ? "په وخت د فرمایشونو لیږل" : (isDari ? "ارسال به‌موقع سفارشات" : "On-Time Dispatch Rate"),
            ["MatchDescription"] = isPashto ? "د انځور او توضیحاتو سره سمون" : (isDari ? "تطابق با تصویر و توضیحات" : "Match with Image & Description"),
            ["TotalRatingsCount"] = isPashto ? "د ۱۲۸ پیرودونکو رایو له مجموعې څخه" : (isDari ? "از مجموع ۱۲۸ رای خریداران" : "from 128 customer ratings"),
            ["BuildQuality"] = isPashto ? "د جوړښت کیفیت: عالي (۴.۹ له ۵)" : (isDari ? "کیفیت ساخت: عالی (۴.۹ از ۵)" : "Build Quality: Excellent (4.9 / 5)"),
            ["ValueForPrice"] = isPashto ? "د بیې په پرتله د پیرود ارزښت: عالي (۴.۸ له ۵)" : (isDari ? "ارزش خرید در برابر قیمت: عالی (۴.۸ از ۵)" : "Value for Price: Excellent (4.8 / 5)"),
            ["InnovationScore"] = isPashto ? "نوښت او کارندوالی: خورا ښه (۴.۷ له ۵)" : (isDari ? "نوآوری و کارایی: بسیار خوب (۴.۷ از ۵)" : "Innovation & Utility: Very Good (4.7 / 5)"),
            ["WriteReview"] = isPashto ? "نوې تبصره ولیکئ" : (isDari ? "ثبت دیدگاه جدید" : "Write a Customer Review"),
            ["ReviewNotice"] = isPashto ? "د نظر لیکلو برخه به د توکو له پیرود وروسته فعاله شي." : (isDari ? "بخش ثبت دیدگاه پس از خرید کالا فعال خواهد شد." : "Review submission will be enabled after purchasing the product."),
            ["RelatedProducts"] = isPashto ? "ورته او وړاندیز شوي محصولات" : (isDari ? "محصولات مشابه و پیشنهادی" : "Related & Recommended Products"),
            ["ViewAllProducts"] = isPashto ? "ټول محصولات لیدل ←" : (isDari ? "مشاهده همه محصولات ←" : "View All Products ←"),
            ["View"] = isPashto ? "لیدل" : (isDari ? "مشاهده" : "View"),
            ["FinalPrice"] = isPashto ? "وروستۍ بیه:" : (isDari ? "قیمت نهایی:" : "Final Price:"),
            ["ProductSpecifications"] = isPashto ? "د توکي ځانګړي مشخصات او جزئیات" : (isDari ? "مشخصات و ویژگی‌های فنی محصول" : "Product Specifications & Details"),
            ["FeatureSpecification"] = isPashto ? "ځانګړتیا / مشخصه" : (isDari ? "ویژگی / مشخصه" : "Feature / Specification"),
            ["ValueDescription"] = isPashto ? "مقدار / توضیحات" : (isDari ? "مقدار / توضیحات" : "Value / Description"),

            // KYC Registration Form
            ["Kyc_Title"] = isPashto ? "د پلورونکي او نمایندګۍ د نوم لیکنې بشپړ فرم (KYC Registration)" : (isDari ? "فرم جامع درخواست فروشندگی و نمایندگی (KYC Registration)" : "Vendor & Agency KYC Registration Form"),
            ["Kyc_Subtitle"] = isPashto ? "د پلورنځي حساب جوړول او د هویت تصدیق (KYC)" : (isDari ? "ایجاد حساب فروشگاهی و احراز هویت (KYC)" : "Create Store Account & Identity Verification (KYC)"),
            ["Kyc_Desc"] = isPashto ? "لاندې معلومات به د حقوقي ارزونې او تصدیق لپاره کارول کیږي." : (isDari ? "اطلاعات زیر جهت بررسی حقوقی و احراز هویت توسط مدیران پلتفرم استفاده خواهد شد." : "The following information will be used for legal review and identity verification by platform admins."),
            ["Kyc_Section1"] = isPashto ? "۱. د هویت معلومات (حقیقي او حقوقي اشخاص)" : (isDari ? "۱. اطلاعات هویتی (اشخاص حقیقی و حقوقی)" : "1. Identity Information (Individuals & Corporate)"),
            ["Kyc_PersonTypeReal"] = isPashto ? "حقیقي شخص (فرد)" : (isDari ? "شخص حقیقی (فرد)" : "Individual (Real Person)"),
            ["Kyc_PersonTypeLegal"] = isPashto ? "حقوقي شخص (شرکت)" : (isDari ? "شخص حقوقی (شرکت)" : "Corporate (Legal Entity)"),
            ["Kyc_FullName"] = isPashto ? "نوم او تخلص (د ملي کارت مطابق)" : (isDari ? "نام و نام خانوادگی (دقیقاً مطابق کارت ملی)" : "Full Name (Matches National ID)"),
            ["Kyc_NationalId"] = isPashto ? "ملي کوډ / د تذکرې شمېره" : (isDari ? "کد ملی / شماره تذکره" : "National ID / Tazkira Number"),
            ["Kyc_BirthDate"] = isPashto ? "د زیږون نیټه" : (isDari ? "تاریخ تولد" : "Date of Birth"),
            ["Kyc_Gender"] = isPashto ? "جنسیت" : (isDari ? "جنسیت" : "Gender"),
            ["Kyc_GenderMale"] = isPashto ? "نارینه (Male)" : (isDari ? "مرد (Male)" : "Male"),
            ["Kyc_GenderFemale"] = isPashto ? "ښځینه (Female)" : (isDari ? "زن (Female)" : "Female"),
            ["Kyc_GenderOther"] = isPashto ? "نور" : (isDari ? "سایر" : "Other"),
            ["Kyc_CompanyName"] = isPashto ? "د شرکت رسمي نوم" : (isDari ? "نام رسمی شرکت" : "Official Company Name"),
            ["Kyc_CompanyNationalId"] = isPashto ? "د شرکت ملي کوډ" : (isDari ? "شناسه ملی شرکت" : "Company National ID"),
            ["Kyc_EconomicCode"] = isPashto ? "اقتصادي کوډ" : (isDari ? "کد اقتصادی" : "Economic Code"),
            ["Kyc_RegistrationNo"] = isPashto ? "د ثبت شمېره" : (isDari ? "شماره ثبت" : "Registration Number"),
            ["Kyc_CompanyType"] = isPashto ? "د شرکت ډول" : (isDari ? "نوع شرکت" : "Company Type"),
            ["Kyc_CeoDetails"] = isPashto ? "د مدیر / استازي نوم او ملي کوډ" : (isDari ? "نام و کد ملی مدیرعامل / نماینده" : "CEO / Representative Name & National ID"),
            ["Kyc_Section2"] = isPashto ? "۲. د اړیکې او موقعیت معلومات" : (isDari ? "۲. اطلاعات تماس و موقعیت مکانی" : "2. Contact & Location Information"),
            ["Kyc_MobileOtp"] = isPashto ? "د موبایل شمیره (د OTP لپاره)" : (isDari ? "شماره موبایل (جهت OTP)" : "Mobile Number (For OTP)"),
            ["Kyc_Email"] = isPashto ? "د بریښنالیک پته" : (isDari ? "آدرس ایمیل" : "Email Address"),
            ["Kyc_Landline"] = isPashto ? "د ښار کوډ سره ثابته تلیفون" : (isDari ? "تلفن ثابت با کد شهر" : "Landline Phone (With City Code)"),
            ["Kyc_ProvinceCity"] = isPashto ? "ولایت او ښار" : (isDari ? "استان و شهر" : "Province & City"),
            ["Kyc_PostalCode"] = isPashto ? "۱۰ رقمی پُستي کوډ" : (isDari ? "کد پستی ۱۰ رقمی" : "10-Digit Postal Code"),
            ["Kyc_ShopSlug"] = isPashto ? "د پلورنځي پیژندل / سلګ (Slug)" : (isDari ? "شناسه / نامک فروشگاه (Slug)" : "Store Identifier / Slug"),
            ["Kyc_ExactAddress"] = isPashto ? "بشپړ پُستي ادرس (ګدام یا فزیکي پلورنځی)" : (isDari ? "آدرس دقیق پستی (انبار یا فروشگاه فیزیکی)" : "Exact Postal Address (Warehouse or Physical Store)"),
            ["Kyc_Section3"] = isPashto ? "۳. د پلورنځي او برانډ معلومات" : (isDari ? "۳. اطلاعات فروشگاه و برند" : "3. Shop & Brand Details"),
            ["Kyc_ShopNameEn"] = isPashto ? "د پلورنځي نوم (English)" : (isDari ? "نام فروشگاه (English)" : "Shop Name (English)"),
            ["Kyc_ShopNamePrs"] = isPashto ? "د پلورنځي نوم (دري)" : (isDari ? "نام فروشگاه (دری)" : "Shop Name (Dari)"),
            ["Kyc_ShopNamePs"] = isPashto ? "د پلورنځي نوم (پښتو)" : (isDari ? "نام فروشگاه (پښتو)" : "Shop Name (Pashto)"),
            ["Kyc_PrimaryCategory"] = isPashto ? "د محصولاتو اصلي کتګورۍ" : (isDari ? "دسته‌بندی اصلی محصولات" : "Primary Product Category"),
            ["Kyc_LogoUrl"] = isPashto ? "د لوګو لینک / پروفایل انځور" : (isDari ? "لینک لوگو / تصویر پروفایل" : "Logo Link / Profile Image"),
            ["Kyc_LogoUpload"] = isPashto ? "د لوګو / پروفایل انځور اپلوډ" : (isDari ? "آپلود لوگو / تصویر پروفایل" : "Upload Logo / Profile Image"),
            ["Kyc_BizDesc"] = isPashto ? "د سوداګرۍ لنډ تفصیل" : (isDari ? "شرح مختصر کسب و کار" : "Brief Business Description"),
            ["Kyc_Section4"] = isPashto ? "۴. مالي او بانکي معلومات (د تصفیې لپاره)" : (isDari ? "۴. اطلاعات مالی و بانکی (جهت تسویه‌حساب)" : "4. Financial & Bank Info (For Settlement)"),
            ["Kyc_Iban"] = isPashto ? "د شبا شمیره (IBAN)" : (isDari ? "شماره شبا (IBAN)" : "IBAN / Sheba Number"),
            ["Kyc_CardNo"] = isPashto ? "د کارت شمیره / ملاتړ حساب" : (isDari ? "شماره کارت / حساب پشتیبان" : "Card Number / Backup Account"),
            ["Kyc_AccountOwner"] = isPashto ? "د حساب خاوند نوم (د ملي کوډ سره سم)" : (isDari ? "نام صاحب حساب (مطابق کدملی)" : "Account Owner Name (Matches National ID)"),
            ["Kyc_Section5"] = isPashto ? "۵. اسناد او تاییدات (د اسنادو اپلوډ)" : (isDari ? "۵. مدارک و تاییدیهها (آپلود مستندات)" : "5. Documents & Approvals (Upload Docs)"),
            ["Kyc_DocNationalId"] = isPashto ? "د ملي کارت انځور" : (isDari ? "تصویر کارت ملی" : "National ID Card Image"),
            ["Kyc_DocLicense"] = isPashto ? "د سوداګرۍ جواز / استازیتوب مکتوب" : (isDari ? "جواز کسب / پروانه / نمایندگی" : "Business License / Agency Letter"),
            ["Kyc_DocVat"] = isPashto ? "د ارزښت اضافه مالیې سند (حقوقي)" : (isDari ? "گواهی ارزش افزوده (حقوقی)" : "VAT Certificate (Corporate)"),
            ["Kyc_Uploaded"] = isPashto ? "✓ اپلوډ شو" : (isDari ? "✓ آپلود شد" : "✓ Uploaded"),
            ["Kyc_SelectFile"] = isPashto ? "📁 د انځور فایل وټاکئ" : (isDari ? "📁 انتخاب فایل تصویر" : "📁 Select Image File"),
            ["Kyc_TermsCheck"] = isPashto ? "ما د نورزي بازار ټول شرایط، مقررات او قرارداد په دقت سره لوستلی او منم یې." : (isDari ? "تمام شرایط، قوانین و قرارداد پلتفرم نورزی بازار را به دقت مطالعه کرده و می‌پذیرم." : "I have carefully read and accept all terms, conditions, and the Noorzai Marketplace agreement."),
            ["Kyc_SubmitVendor"] = isPashto ? "د پلورونکي غوښتنلیک ثبت او لیږل (Submit KYC)" : (isDari ? "ثبت نهایی و ارسال درخواست فروشندگی (Submit KYC)" : "Final Submit & Send Vendor Application (Submit KYC)"),
            ["Kyc_SubmitAgency"] = isPashto ? "د نمایندګۍ غوښتنلیک ثبت او لیږل (Submit KYC)" : (isDari ? "ثبت نهایی و ارسال درخواست نمایندگی (Submit KYC)" : "Final Submit & Send Agency Application (Submit KYC)"),

            // Admin KYC Modal
            ["Kyc_ReviewFile"] = isPashto ? "🏢 د هویت تصدیق او د غوښتونکي اسنادو دوسیه (KYC Review)" : (isDari ? "🏢 پرونده احراز هویت و مدارک متقاضی (KYC Review)" : "🏢 Applicant Identity & Document File (KYC Review)"),
            ["Kyc_Section1Title"] = isPashto ? "۱. د هویت معلومات" : (isDari ? "۱. اطلاعات هویتی" : "1. Identity Information"),
            ["Kyc_LegalPerson"] = isPashto ? "🏢 حقوقي شخص (شرکت)" : (isDari ? "🏢 شخص حقوقی (شرکت)" : "🏢 Corporate (Legal Entity)"),
            ["Kyc_RealPerson"] = isPashto ? "👤 حقیقي شخص (فرد)" : (isDari ? "👤 شخص حقیقی (فرد)" : "👤 Individual (Real Person)"),
            ["Kyc_FullNameLbl"] = isPashto ? "نوم او تخلص:" : (isDari ? "نام و نام خانوادگی:" : "Full Name:"),
            ["Kyc_NationalIdLbl"] = isPashto ? "ملي کوډ / تذکره:" : (isDari ? "کد ملی / تذکره:" : "National ID / Tazkira:"),
            ["Kyc_BirthDateLbl"] = isPashto ? "د زیږون نیټه:" : (isDari ? "تاریخ تولد:" : "Date of Birth:"),
            ["Kyc_GenderLbl"] = isPashto ? "جنسیت:" : (isDari ? "جنسیت:" : "Gender:"),
            ["Kyc_CompanyNameLbl"] = isPashto ? "د شرکت نوم:" : (isDari ? "نام شرکت:" : "Company Name:"),
            ["Kyc_CompanyNationalIdLbl"] = isPashto ? "د شرکت ملي شناسه:" : (isDari ? "شناسه ملی شرکت:" : "Company National ID:"),
            ["Kyc_EcoCodeLbl"] = isPashto ? "اقتصادي کوډ:" : (isDari ? "کد اقتصادی:" : "Economic Code:"),
            ["Kyc_RegNoLbl"] = isPashto ? "د ثبت شمېره:" : (isDari ? "شماره ثبت:" : "Registration Number:"),
            ["Kyc_CompanyTypeLbl"] = isPashto ? "د شرکت ډول:" : (isDari ? "نوع شرکت:" : "Company Type:"),
            ["Kyc_CeoLbl"] = isPashto ? "مدیر / استازی:" : (isDari ? "مدیرعامل / نماینده:" : "CEO / Representative:"),
            ["Kyc_Section2Title"] = isPashto ? "۲. د اړیکې او موقعیت معلومات" : (isDari ? "۲. تماس و موقعیت مکانی" : "2. Contact & Location"),
            ["Kyc_MobileLbl"] = isPashto ? "موبایل (OTP):" : (isDari ? "موبایل (OTP):" : "Mobile (OTP):"),
            ["Kyc_EmailLbl"] = isPashto ? "ایمیل:" : (isDari ? "ایمیل:" : "Email:"),
            ["Kyc_LandlineLbl"] = isPashto ? "ثابته تلیفون:" : (isDari ? "تلفن ثابت:" : "Landline:"),
            ["Kyc_ProvinceCityLbl"] = isPashto ? "ولایت او ښار:" : (isDari ? "استان و شهر:" : "Province & City:"),
            ["Kyc_PostalCodeLbl"] = isPashto ? "پُستي کوډ:" : (isDari ? "کد پستی ۱۰ رقمی:" : "Postal Code:"),
            ["Kyc_SlugLbl"] = isPashto ? "د لینک نوم (Slug):" : (isDari ? "نامک لینک (Slug):" : "Link Slug:"),
            ["Kyc_ExactAddrLbl"] = isPashto ? "د ګدام/پلورنځي دقیق ادرس:" : (isDari ? "آدرس دقیق انبار/فروشگاه:" : "Exact Warehouse/Store Address:"),
            ["Kyc_Section3Title"] = isPashto ? "۳. د پلورنځي او برانډ معلومات" : (isDari ? "۳. اطلاعات فروشگاه و برند" : "3. Shop & Brand Info"),
            ["Kyc_NameEnLbl"] = isPashto ? "نوم (English):" : (isDari ? "نام (English):" : "Name (English):"),
            ["Kyc_NamePrsLbl"] = isPashto ? "نوم (دري):" : (isDari ? "نام (دری):" : "Name (Dari):"),
            ["Kyc_NamePsLbl"] = isPashto ? "نوم (پښتو):" : (isDari ? "نام (پښتو):" : "Name (Pashto):"),
            ["Kyc_MainCatLbl"] = isPashto ? "اصلي کتګوري:" : (isDari ? "دسته‌بندی اصلی:" : "Main Category:"),
            ["Kyc_BizDescLbl"] = isPashto ? "د سوداګرۍ تفصیل:" : (isDari ? "شرح کسب و کار:" : "Business Description:"),
            ["Kyc_Section4Title"] = isPashto ? "۴. مالي او بانکي معلومات" : (isDari ? "۴. اطلاعات مالی و بانکی" : "4. Financial & Bank Info"),
            ["Kyc_IbanLbl"] = isPashto ? "د شبا شمیره (IBAN):" : (isDari ? "شماره شبا (IBAN):" : "IBAN:"),
            ["Kyc_CardLbl"] = isPashto ? "د کارت/حساب شمیره:" : (isDari ? "شماره کارت/حساب:" : "Card/Account No:"),
            ["Kyc_OwnerLbl"] = isPashto ? "د حساب خاوند:" : (isDari ? "صاحب حساب:" : "Account Owner:"),
            ["Kyc_Section5Title"] = isPashto ? "۵. اپلوډ شوي اسناد او مستندات" : (isDari ? "۵. مدارک و مستندات آپلود شده" : "5. Uploaded Documents"),
            ["Kyc_ViewFile"] = isPashto ? "فایل وګورئ" : (isDari ? "مشاهده فایل" : "View File"),
            ["Kyc_NotRegistered"] = isPashto ? "نه دی ثبت شوی" : (isDari ? "ثبت نشده" : "Not Registered"),
            ["Kyc_ApproveAgency"] = isPashto ? "✓ تایید او نمایندګي ورکول" : (isDari ? "✓ تایید و اعطای نمایندگی" : "✓ Approve & Grant Agency"),
            ["Kyc_RejectRequest"] = isPashto ? "✕ غوښتنه ردول" : (isDari ? "✕ رد درخواست" : "✕ Reject Request"),
            ["Kyc_NationalIdCardFile"] = isPashto ? "کارت ملی" : (isDari ? "کارت ملی" : "National ID"),
            ["Kyc_BusinessLicenseFile"] = isPashto ? "جواز کسب" : (isDari ? "جواز کسب" : "Business License"),
            ["Kyc_VatFile"] = isPashto ? "ارزش افزوده" : (isDari ? "ارزش افزوده" : "VAT"),
            ["Kyc_Tab1"] = isPashto ? "۱. هویتی" : (isDari ? "۱. هویتی" : "1. Identity"),
            ["Kyc_Tab2"] = isPashto ? "۲. اړیکه" : (isDari ? "۲. تماس" : "2. Contact"),
            ["Kyc_Tab3"] = isPashto ? "۳. سوداګرۍ" : (isDari ? "۳. کسب‌وکار" : "3. Business"),
            ["Kyc_Tab4"] = isPashto ? "۴. مالي" : (isDari ? "۴. مالی" : "4. Financial"),
            ["Kyc_Tab5"] = isPashto ? "۵. اسناد" : (isDari ? "۵. مدارک" : "5. Documents"),

            // Decision Modal
            ["Kyc_ApproveTitle"] = isPashto ? "د نمایندګۍ غوښتنې حتمي تاییدول" : (isDari ? "تایید نهایی درخواست نمایندگی" : "Approve Agency Application"),
            ["Kyc_RejectTitle"] = isPashto ? "د نمایندګۍ غوښتنې ردول" : (isDari ? "رد درخواست نمایندگی" : "Reject Agency Application"),
            ["Kyc_ApproveReasonLbl"] = isPashto ? "د تایید توضیحات یا علت (ارامښت/اختیاري):" : (isDari ? "توضیحات یا ملاحظات تایید (اختیاری):" : "Approval Notes / Reason (Optional):"),
            ["Kyc_RejectReasonLbl"] = isPashto ? "د غوښتنې د ردولو علت (حتمي/اجباري):" : (isDari ? "دلیل رد درخواست (اجباری):" : "Rejection Reason (Required):"),
            ["Kyc_ReasonPlaceholder"] = isPashto ? "د غوښتونکي لپاره د پام وړ ټکي او توضیحات ولیکئ..." : (isDari ? "توضیحات یا دلایل مربوطه را جهت اطلاع متقاضی وارد کنید..." : "Enter decision notes or reasons for the applicant..."),
            ["Kyc_ConfirmDecision"] = isPashto ? "ثبت او خبرتیا لیږل" : (isDari ? "ثبت و ارسال تصمیم" : "Confirm & Send Notification"),
            ["Kyc_CancelDecision"] = isPashto ? "انصراف" : (isDari ? "انصراف" : "Cancel"),
            ["AllVendorsFilter"] = isPashto ? "ټول پلورنځي (All Vendors)" : (isDari ? "همه فروشگاه‌ها (All Vendors)" : "All Vendors"),

            // User Profile
            ["BackToHome"] = isPashto ? "کور پاڼې ته ستنېدل" : (isDari ? "بازگشت به صفحه اصلی" : "Back to Homepage"),
            ["MyProfile"] = isPashto ? "زما پروفایل" : (isDari ? "پروفایل کاربری من" : "My Profile"),
            ["ProfileHeaderDesc"] = isPashto ? "خپل شخصي معلومات، د اړیکو تفصیلات، او د تحویلۍ پته اداره کړئ." : (isDari ? "اطلاعات شخصی، مشخصات تماس و نشانی دقیق تحویل سفارشات خود را مدیریت کنید." : "Manage your personal details, contact information, and shipping address."),
            ["ProfileCompletionStatus"] = isPashto ? "د پروفایل د بشپړیدو کچه" : (isDari ? "وضعیت تکمیل پروفایل" : "Profile Completion"),
            ["ProfileIncompleteTitle"] = isPashto ? "د پروفایل نیمګړتیا" : (isDari ? "پروفایل ناقص است" : "Profile Incomplete"),
            ["IncompleteProfileWarning"] = isPashto ? "مهرباني وکړئ د فرمایش ورکولو دمخه خپل بشپړ نوم، د تلیفون شمیره، او تحویلي پته بشپړه کړئ." : (isDari ? "لطفاً برای ثبت و پیگیری سریع سفارش، نام، شماره تماس و آدرس دقیق پستی خود را تکمیل نمایید." : "Please complete your full name, phone number, and delivery address before placing an order."),
            ["PersonalInfo"] = isPashto ? "شخصي معلومات" : (isDari ? "اطلاعات هویتی و فردی" : "Personal Information"),
            ["ContactAndAddress"] = isPashto ? "د اړیکو معلومات او پته" : (isDari ? "مشخصات تماس و نشانی تحویل" : "Contact & Delivery Address"),
            ["AccountSecurity"] = isPashto ? "امنیت او د کارونکي حساب" : (isDari ? "امنیت و حساب کاربری" : "Account & Security"),
            ["FullNameLabel"] = isPashto ? "بشپړ نوم" : (isDari ? "نام و نام خانوادگی" : "Full Name"),
            ["PhoneNumberLabel"] = isPashto ? "د اړیکې / ګرځنده شمیره" : (isDari ? "شماره تماس / همراه" : "Phone Number"),
            ["EmailLabel"] = isPashto ? "بریښنالیک پته" : (isDari ? "آدرس ایمیل" : "Email Address"),
            ["AddressLabel"] = isPashto ? "د فرمایش تحویلي پته" : (isDari ? "نشانی پستی دقیق جهت دریافت سفارش" : "Delivery Address"),
            ["SaveProfile"] = isPashto ? "د پروفایل معلومات خوندي کول" : (isDari ? "ذخیره و بروزرسانی اطلاعات" : "Save Profile Details"),
            ["ProfileUpdatedSuccess"] = isPashto ? "د پروفایل معلومات په بریالیتوب سره تازه شول!" : (isDari ? "اطلاعات پروفایل با موفقیت بروزرسانی شد!" : "Profile details updated successfully!"),
            ["AccountRole"] = isPashto ? "د حساب رول" : (isDari ? "سطح دسترسی" : "Account Role"),
            ["ReferralCodeLabel"] = isPashto ? "ستاسو د بلنې کوډ" : (isDari ? "کد معرف شما" : "Your Referral Code"),
            ["CopyReferralLink"] = isPashto ? "د بلنې لینک کاپي کول" : (isDari ? "کپی لینک دعوت اختصاصی" : "Copy Referral Link"),
            ["MemberSince"] = isPashto ? "د غړیتوب نیټه" : (isDari ? "تاریخ عضویت" : "Member Since"),
            ["VerifiedAccount"] = isPashto ? "تایید شوی حساب" : (isDari ? "حساب کاربری تایید شده" : "Verified Account"),
            ["AllFieldsRequired"] = isPashto ? "ټولې ساحې باید ډکې شي." : (isDari ? "تکمیل تمام فیلدهای ستاره‌دار الزامی است." : "All required fields must be filled."),
            ["Role_SuperAdmin"] = isPashto ? "سوپر اډمین" : (isDari ? "مدیر ارشد کل" : "Super Admin"),
            ["Role_Admin"] = isPashto ? "اداره کوونکی" : (isDari ? "مدیر سیستم" : "System Admin"),
            ["Role_Vendor"] = isPashto ? "پلورونکی" : (isDari ? "فروشنده" : "Vendor"),
            ["Role_AgencyRep"] = isPashto ? "د نمایندګۍ استازی" : (isDari ? "نماینده رسمی" : "Agency Rep"),
            ["Role_Marketer"] = isPashto ? "بازاریاب" : (isDari ? "بازاریاب و معرف" : "Marketer"),
            ["Role_Customer"] = isPashto ? "پیرودونکی" : (isDari ? "مشتری / کاربر" : "Customer"),
            ["MyCustomers"] = isPashto ? "زما مشتریان او پیرودنې" : (isDari ? "مشتریان و پورسانت‌های من" : "My Customers & Referrals"),

            // Cart & Checkout
            ["OrderSummary"] = isPashto ? "د فرمایش لنډیز" : (isDari ? "خلاصه سفارش" : "Order Summary"),
            ["Subtotal"] = isPashto ? "د توکو مجموعه" : (isDari ? "جمع اقلام" : "Subtotal"),
            ["ShippingFee"] = isPashto ? "د لیږد لګښت" : (isDari ? "هزینه ارسال" : "Shipping Fee"),
            ["FreeShipping"] = isPashto ? "وړیا لیږد" : (isDari ? "ارسال رایگان" : "Free Delivery"),
            ["TotalAmount"] = isPashto ? "ټولټال د ورکړې وړ پیسې" : (isDari ? "مبلغ کل قابل پرداخت" : "Total Amount"),
            ["PlaceOrder"] = isPashto ? "د فرمایش ثبت او نهایی کول" : (isDari ? "ثبت و پرداخت نهایی سفارش" : "Place Order Now"),
            ["OrderSubmittedTitle"] = isPashto ? "ستاسو فرمایش په بریالیتوب سره ثبت شو!" : (isDari ? "سفارش شما با موفقیت ثبت شد!" : "Order Placed Successfully!"),
            ["OrderSubmittedDesc"] = isPashto ? "ستاسو فرمایش تر پروسس لاندې دی او ډیر ژر به ولیږل شي." : (isDari ? "سفارش شما در مرحله پردازش قرار گرفت و به زودی ارسال خواهد شد." : "Your order is being processed and will be shipped shortly."),
            ["ContinueShopping"] = isPashto ? "د نورو توکو پیرودل" : (isDari ? "ادامه خرید و مشاهده کالاها" : "Continue Shopping"),
            ["EmptyCartTitle"] = isPashto ? "ستاسو د پیرودلو ټوکرۍ خالي ده" : (isDari ? "سبد خرید شما خالی است" : "Your Shopping Cart is Empty"),
            ["EmptyCartDesc"] = isPashto ? "هغه توکي چې غواړئ دلته اضافه کړئ ترڅو وښودل شي." : (isDari ? "کالاهای مورد نظر خود را به سبد خرید اضافه کنید تا در این بخش نمایش داده شوند." : "Browse our catalog to discover and add products to your cart."),
            ["ExploreCatalog"] = isPashto ? "د توکو لټون او پیرود" : (isDari ? "مشاهده و خرید محصولات" : "Explore Products"),
            ["ClearCart"] = isPashto ? "ټوکرۍ خالي کول" : (isDari ? "خالی کردن سبد" : "Clear Cart"),
            ["HaveReferralCode"] = isPashto ? "د بلنې یا تخفیف کوډ لرئ؟" : (isDari ? "کد معرف یا تخفیف دارید؟" : "Have a Referral Code?"),
            ["ReferralApplied"] = isPashto ? "د بلنې کوډ تطبیق شو" : (isDari ? "کد معرف فعال شد" : "Referral Code Applied"),
            ["SecureCheckoutBadge"] = isPashto ? "۱۰۰٪ خوندي او باوري پیرود" : (isDari ? "ضمانت اصالت و خرید ۱۰۰٪ امن" : "100% Secure Checkout Guarantee"),
            ["ItemsInCart"] = isPashto ? "په ټوکرۍ کې توکي" : (isDari ? "کالا در سبد" : "items in cart"),
            ["SizeLabel"] = isPashto ? "اندازه" : (isDari ? "سایز" : "Size"),
            ["ColorLabel"] = isPashto ? "رنګ" : (isDari ? "رنگ" : "Color")
        };

        return Task.FromResult(Result.Success(strings));
    }
}
